### ISSUE TITLE
Unable to Move from Bed after Sleep

### ISSUE THREAD

**Issue by slidingmike** [Quetzi/Morpheus#20]
Players are reporting they are unable to exit the bed after sleep. Requires the player to be kicked or close out minecraft completely.

Morpheus 3.1.5
Forge 1976
Minecraft 1.9.4

**Comment by Quetzi** [comment]
Can you replicate this with just Morpheus installed? If this was something Morpheus related I would have seen the issue on Forgecraft or FTB One. It is likely some other mod in your pack causing problems.

**Comment by codahq** [comment]
It's definitely related to Morpheus.  If you read your comments on curse you will see many people experiencing this issue.  They just don't know to hit your repo's issue page to report.  

I can definitely say this is related to Morpheus.  I have users reporting the issue with the mod freshly installed.  The server only runs two mods; this mod and another  unreleased private mod.  The unreleased private mod has not changed in over 6 months.  This mod was introduced and the problem occurs.  Forge was not updated.  This happens in Minecraft 1.10.2.  

If it isn't your mod then I'm wondering if you have found some bug in one of Forge's events that isn't used often.  Either way, it's sort of on you to fix.  I can supply forge version if necessary but from your comments it looks like it is happening across the board so it doesn't matter.  Latest version of Morpheus.

**Comment by Quetzi** [comment]
I can assure you that this is nothing to do with Morpheus. For starters, I don't do anything that could possibly cause this to happen, I don't use the forge sleep events. Secondly, this is a well known and widely reported vanilla bug, so no, it isn't on me to fix, it's on Mojang to fix, except they won't in 1.10 because they stopped working on that a while ago. If you are only running a couple of mods your best bet is to move to 1.11 where, hopefully, Mojang fixed the bug. Although the issue is still open, so probably not. https://bugs.mojang.com/plugins/servlet/mobile#issue/MC-92216

**Comment by codahq** [comment]
Interesting.  I stand corrected.  Thank you for linking the Mojang issue.  I guess my users made a connection that didn't exist.  Why have so many people associated this bug to your mod?

**Comment by Quetzi** [comment]
Because it's easier to assume that a mod is at fault than it is to find out it's Vanilla. Considering the bug has been there since the start of 1.10 and continues through the current snapshots I'm guessing it isn't high on their list of things to fix
