### ISSUE TITLE
Ignore Spectators

### ISSUE THREAD

**Issue by dbkynd** [Quetzi/Morpheus#62]
Hello, I was wondering if ignoring players that are in spectator mode might be a good addition to this mod. Thanks!

**Comment by Quetzi** [comment]
Hi, what is the use case for this? When would you have players in spectator mode in a survival world?

**Comment by zpetty33** [comment]
On Hardcore setups, players who die are forced into spectator for the remainder of that map, until it is reset.

**Comment by dbkynd** [comment]
On survival servers, admins and OPS fly around in spectator mode to monitor player activity. It would be nice if they weren't counted toward the total. Also Hardcore. yeah.

**Comment by Yamza** [comment]
I can see the benefit in this, but it also easy enough to set the value to something appropriate knowing there may be admin/spectators on. 

If you are going to do this i would suggest also having is such that anyone in creative wont, count as well as spectator.

**Comment by Quetzi** [comment]
From version .32 spectators and creative players are ignored

**Comment by C0rn3j** [comment]
@Quetzi Would you be so kind and backport this change to the 1.12.2 branch?

I realize you seem to have moved on to 1.14.x only, but since only 10%~ of the mods I use have been ported so far, I'm stuck with the 1.12 version and BetterPortals clashes quite heavily with older Morpheus, since it generates a spectator per-dimension.

If not I'll just stick with working around this by modifying `SleeperPerc`.

**Comment by Quetzi** [comment]
If I find the time I may back port it, but I wouldn't count on it. Your issue sounds like a bug report for BetterPortals.

**Comment by C0rn3j** [comment]
That's actually how I got here (see the reference).
I'll live with the config hack then.
