### ISSUE TITLE
Morpheus overrides Minecraft Bed setspawn

### ISSUE THREAD

**Issue by UnRealDinnerbone** [Quetzi/Morpheus#74]
In Minecraft 1.15 they added the feature where when you right-click a bed it sets your spawn making it spam your chat that your spawn point has been changed.

https://unreal.codes/2020/3/10/1583859341450-javaw_6ipYeaG7cl.png

**Comment by Quetzi** [comment]
Morpheus-1.15.2-4.2.50.jar should have a fix for this, I've cleaned up the calculation for the players distance from their spawn point so that it doesn't unnecessarily set the spawn. I've also removed the message that I send to the player as the function I'm using to set the spawn now sends a message to the player.
