### ISSUE TITLE
Incompatibility with "day sleeping" mods

### ISSUE THREAD

**Issue by maxanier** [Quetzi/Morpheus#84]
Morpheus does not work with Vampirism's coffin sleep (during the day) on 1.15 (probably 1.14 and 1.16 as well): https://github.com/TeamLapen/Vampirism/issues/776
It skips to the next morning instead of evening.

Are you using ForgeEventFactory.onSleepFinished to determine the wakeup time?
See e.g. https://github.com/Vazkii/Quark/issues/2036

**Comment by Quetzi** [comment]
This is not a Morpheus issue. Morpheus has API functions that allow mods that do non standard things with sleep in the overworld to redefine what happens when sleep is successful. The Vampirism team just need to add support.

**Comment by maxanier** [comment]
However, this is a Forge feature which aims to support mod interactions like this. Therefore, I don't see why using a Morpheus specific API is required.
Besides, I can't find the morpheus API (for 1.14+) here.

**Comment by macks2008** [comment]
yeah actually this repository doesn't look like it's been updated in 3 years... so that response isn't very helpful, especially considering you're talking to the exact same person that needs to know (Vampirism lead dev ^^)

**Comment by lunofe** [comment]
@Quetzi would you mind reconsidering this?

**Comment by Twisted-Code** [comment]
okay if you can't be bothered to actually answer questions properly and are just going to close things without following up, I'm not going to bother with any further bug reports, internal, compatibility, or otherwise. Not worth my effort. Sorry man...
(yes I know I technically am not the one that opened this, but I'm the one that reported it to Max. The point is the same)

**Comment by codec-d** [comment]
why was this closed its clearly a morpheus problem for not using Forge features and trying to reinvent the wheel
